#!/usr/bin/env node

import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const lockPath = path.join(root, 'package-lock.json');
const inventoryPath = path.join(root, 'docs', 'DEPENDENCY_LICENSES.md');
const noticesPath = path.join(root, 'public', 'third-party-licenses.txt');
const generatedStart = '----- BEGIN GENERATED NPM DEPENDENCY NOTICES -----';
const generatedEnd = '----- END GENERATED NPM DEPENDENCY NOTICES -----';
const checkOnly = process.argv.slice(2).includes('--check');
const unknownArguments = process.argv.slice(2).filter((argument) => argument !== '--check');

if (unknownArguments.length > 0) {
  fail(`Unknown argument${unknownArguments.length === 1 ? '' : 's'}: ${unknownArguments.join(', ')}`);
}

const lock = JSON.parse(fs.readFileSync(lockPath, 'utf8'));
const entries = Object.entries(lock.packages ?? {})
  .filter(([lockEntryPath]) => lockEntryPath !== '')
  .map(([lockEntryPath, metadata]) => ({
    lockEntryPath,
    name: packageNameFromLockPath(lockEntryPath),
    version: metadata.version ?? 'UNKNOWN',
    license: metadata.license ?? 'UNKNOWN',
    dev: metadata.dev === true,
    optional: metadata.optional === true,
  }))
  .sort((left, right) => compare(left.lockEntryPath, right.lockEntryPath));

const inventory = renderInventory(entries);
const mandatoryProductionEntries = entries.filter((entry) => !entry.dev && !entry.optional);
const dependencyNotices = renderDependencyNotices(mandatoryProductionEntries);

if (checkOnly) {
  const stale = [];
  if (readIfPresent(inventoryPath) !== inventory) stale.push(relative(inventoryPath));

  const existingNotices = readIfPresent(noticesPath);
  const generatedNotices = extractGeneratedNotices(existingNotices);
  if (generatedNotices !== dependencyNotices) stale.push(relative(noticesPath));

  if (stale.length > 0) {
    fail(`License report is stale: ${stale.join(', ')}. Run node scripts/license-report.mjs.`);
  }

  console.log(`License report is current (${entries.length} lock entries; ${mandatoryProductionEntries.length} mandatory production notices).`);
} else {
  fs.mkdirSync(path.dirname(inventoryPath), { recursive: true });
  fs.mkdirSync(path.dirname(noticesPath), { recursive: true });
  fs.writeFileSync(inventoryPath, inventory);
  fs.writeFileSync(noticesPath, mergeGeneratedNotices(readIfPresent(noticesPath), dependencyNotices));
  console.log(`Wrote ${relative(inventoryPath)} and ${relative(noticesPath)}.`);
}

function renderInventory(dependencies) {
  const licenseCounts = new Map();
  for (const dependency of dependencies) {
    licenseCounts.set(dependency.license, (licenseCounts.get(dependency.license) ?? 0) + 1);
  }

  const mandatoryProductionCount = dependencies.filter((entry) => !entry.dev && !entry.optional).length;
  const devCount = dependencies.filter((entry) => entry.dev).length;
  const optionalCount = dependencies.filter((entry) => entry.optional).length;
  const countRows = [...licenseCounts.entries()]
    .sort(([left], [right]) => compare(left, right))
    .map(([license, count]) => `| ${cell(license)} | ${count} |`)
    .join('\n');
  const inventoryRows = dependencies
    .map((entry) => `| ${cell(entry.lockEntryPath)} | ${cell(entry.name)} | ${cell(entry.version)} | ${cell(entry.license)} | ${yesNo(entry.dev)} | ${yesNo(entry.optional)} |`)
    .join('\n');

  return `# Dependency license metadata\n\n` +
    `Generated by \`node scripts/license-report.mjs\` from \`package-lock.json\`.\n\n` +
    `This inventory reports the license metadata and dependency flags recorded in the lockfile. It is not a full license audit: it does not inspect every source archive or bundled asset, decide license compatibility, identify every copyright holder, or give legal advice. Optional packages are listed from the lockfile even when they are not installed on the current platform.\n\n` +
    `- Dependency lock entries: ${dependencies.length} (the root project entry is excluded)\n` +
    `- Mandatory production entries (\`dev !== true\` and \`optional !== true\`): ${mandatoryProductionCount}\n` +
    `- Entries marked as development dependencies: ${devCount}\n` +
    `- Entries marked as optional: ${optionalCount}\n\n` +
    `## Declared license counts\n\n` +
    `| License metadata | Entries |\n| --- | ---: |\n${countRows}\n\n` +
    `## Lockfile inventory\n\n` +
    `| Lock path | Package | Version | License metadata | Dev | Optional |\n` +
    `| --- | --- | --- | --- | :---: | :---: |\n${inventoryRows}\n`;
}

function renderDependencyNotices(dependencies) {
  const sections = dependencies.map(renderPackageNotice).join('\n\n');
  return `${generatedStart}\n` +
    `THIRD-PARTY DEPENDENCY LICENSES\n\n` +
    `Generated from installed mandatory production packages recorded in package-lock.json.\n` +
    `Included entries have neither dev nor optional set to true. Package versions and license\n` +
    `metadata come from the lockfile; license text comes from the installed package.\n\n` +
    `Coverage: ${dependencies.length} mandatory production dependency lock entries. This file does\n` +
    `not by itself cover development or optional dependencies, fonts, soundfonts, sample scores,\n` +
    `the easy-score project license, operating-system packages, or container base-image packages.\n\n` +
    `${sections}\n` +
    `${generatedEnd}\n`;
}

function renderPackageNotice(entry) {
  const packageDirectory = path.join(root, entry.lockEntryPath);
  const packageJsonPath = path.join(packageDirectory, 'package.json');
  if (!fs.existsSync(packageJsonPath)) {
    fail(`Mandatory production package is not installed: ${entry.lockEntryPath}`);
  }

  const installed = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
  if (installed.version !== entry.version) {
    fail(`Installed version mismatch for ${entry.name}: lockfile has ${entry.version}, installed package has ${installed.version ?? 'UNKNOWN'}`);
  }

  const heading = `${'='.repeat(78)}\n${entry.name} ${entry.version}\nDeclared license: ${entry.license}\n${'='.repeat(78)}`;

  if (entry.name === 'jszip') {
    const source = normalizedRead(path.join(packageDirectory, 'LICENSE.markdown'));
    const start = source.indexOf('The MIT License');
    const end = source.indexOf('\n\nGPL version 3', start);
    if (start < 0 || end < 0) fail('Could not locate JSZip MIT license section.');
    return `${heading}\nLicense selection: JSZip is used under the MIT option of its MIT OR GPL license.\nSource: LICENSE.markdown (complete MIT section only)\n\n${source.slice(start, end).trimEnd()}`;
  }

  if (entry.name === 'pako') {
    const mit = normalizedRead(path.join(packageDirectory, 'LICENSE'));
    const zlib = normalizedRead(path.join(packageDirectory, 'lib', 'zlib', 'README'));
    return `${heading}\nSource: LICENSE\n\n${mit}\n\nSource: lib/zlib/README (zlib license and copyright notice)\n\n${zlib}`;
  }

  if (entry.name === 'isarray') {
    const readme = normalizedRead(path.join(packageDirectory, 'README.md'));
    const start = readme.indexOf('## License');
    if (start < 0) fail('Could not locate isarray license section in README.md.');
    return `${heading}\nSource: README.md (license section; the package has no separate license file)\n\n${readme.slice(start).trimEnd()}`;
  }

  const licenseFiles = fs.readdirSync(packageDirectory, { withFileTypes: true })
    .filter((item) => item.isFile() && /^(?:licen[cs]e|copying|notice)(?:[-._].*)?$/i.test(item.name))
    .map((item) => item.name)
    .sort(compare);
  if (licenseFiles.length === 0) {
    fail(`No packaged license file found for mandatory production package ${entry.name}.`);
  }

  const texts = licenseFiles.map((fileName) => `Source: ${fileName}\n\n${normalizedRead(path.join(packageDirectory, fileName))}`);
  return `${heading}\n${texts.join('\n\n')}`;
}

function extractGeneratedNotices(contents) {
  const start = contents.indexOf(generatedStart);
  const end = contents.indexOf(generatedEnd, start);
  if (start < 0 || end < 0) return '';
  return contents.slice(start, end + generatedEnd.length) + '\n';
}

function mergeGeneratedNotices(existing, generated) {
  const start = existing.indexOf(generatedStart);
  const end = existing.indexOf(generatedEnd, start);
  if (start >= 0 && end >= 0) {
    return existing.slice(0, start) + generated + existing.slice(end + generatedEnd.length).replace(/^\n?/, '');
  }

  if (existing.trim() !== '') {
    return generated + '\n' + existing.replace(/^\n+/, '');
  }

  const manualSection = `\n----- ADDITIONAL THIRD-PARTY ASSET NOTICES -----\n\n` +
    `No additional asset notices have been recorded here yet. Fonts, soundfonts, and sample\n` +
    `scores require separate review because they are not represented by package-lock.json.\n`;
  return generated + manualSection;
}

function packageNameFromLockPath(lockEntryPath) {
  const marker = 'node_modules/';
  const index = lockEntryPath.lastIndexOf(marker);
  return lockEntryPath.slice(index + marker.length);
}

function normalizedRead(filePath) {
  return fs.readFileSync(filePath, 'utf8').replace(/\r\n?/g, '\n').trimEnd();
}

function readIfPresent(filePath) {
  return fs.existsSync(filePath) ? fs.readFileSync(filePath, 'utf8') : '';
}

function relative(filePath) {
  return path.relative(root, filePath);
}

function compare(left, right) {
  return left < right ? -1 : left > right ? 1 : 0;
}

function cell(value) {
  return String(value).replaceAll('\\', '\\\\').replaceAll('|', '\\|').replaceAll('\n', ' ');
}

function yesNo(value) {
  return value ? 'yes' : 'no';
}

function fail(message) {
  console.error(message);
  process.exit(1);
}
